sudo: required
services:
  - docker
  
before_install:
  - docker build -t ydockerr/docker-reactApp -f Dockerfile.dev .
  
script:
  - docker run -e CI=true ydockerr/docker-reactApp npm run test 


after_success:
  - docker build -t ydockerr/docker-reactApp .
  
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ydockerr/docker-reactApp
 

